name: Trigger auto deployment for container-app-tqchxnfa5uohu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'fastify-api-server/**'
    - '.github/workflows/container-app-tqchxnfa5uohu-AutoDeployTrigger-9a69569d-a85e-437c-b7b3-cf4d2028d7a1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPTQCHXNFA5UOHU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPTQCHXNFA5UOHU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPTQCHXNFA5UOHU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/fastify-api-server 
          registryUrl: defaultacrcontainerregistry936e.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPTQCHXNFA5UOHU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPTQCHXNFA5UOHU_REGISTRY_PASSWORD }}
          containerAppName: container-app-tqchxnfa5uohu
          resourceGroup: shopathomeangularae09b101
          imageToBuild: defaultacrcontainerregistry936e.azurecr.io/container-app-tqchxnfa5uohu:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


